@rooturl = https://financetracker-backend-w78e.onrender.com/api/v1
@userEP = {{rooturl}}/users

@transactionEP = {{rooturl}}/transactions



# registering new user 
POST {{userEP}}/register
Content-Type: application/json

{
    "username" : "asertkdhgfk",
    "email" : "sr34dfg@gmail.com",
    "password" : "password"
}

###
# log in 
POST {{userEP}}/login
Content-Type: application/json

{
     "email" : "ram@gmail.com",
    "password" : "123"

}
 
###
GET {{userEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbUBnbWFpbC5jb20iLCJpYXQiOjE3Mzg2Mzg2MzEsImV4cCI6MTczODcyNTAzMX0.CUKN0wqIrX61QUsMcCEL-iBXaHSH9SWDckS21Q1AoPM

###
# creating the transactions
POST {{transactionEP}}/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbUBnbWFpbC5jb20iLCJpYXQiOjE3MzkwNTgzNTksImV4cCI6MTczOTE0NDc1OX0.AwKazNCZLV6m75_yRm2R0kMeEhYBb2i-YyYqLoSF5sc

{
    "type": "Expense",
    "amount": 700,
    "date": "01-21-2025",
    "description" : "hello"
}

###
GET {{transactionEP}}
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbUBnbWFpbC5jb20iLCJpYXQiOjE3MzkwNjA5OTQsImV4cCI6MTczOTE0NzM5NH0.M1FTLShoWBq-DdQfdH2B3Jq-n8XnVUvss3Fw0DAN0oQ


###
DELETE {{transactionEP}}/delete/67a7ece669e631a7e590fb05
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbUBnbWFpbC5jb20iLCJpYXQiOjE3MzkwNjA5OTQsImV4cCI6MTczOTE0NzM5NH0.M1FTLShoWBq-DdQfdH2B3Jq-n8XnVUvss3Fw0DAN0oQ

###

DELETE {{transactionEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbUBnbWFpbC5jb20iLCJpYXQiOjE3MzkwNjA5OTQsImV4cCI6MTczOTE0NzM5NH0.M1FTLShoWBq-DdQfdH2B3Jq-n8XnVUvss3Fw0DAN0oQ
Content-Type: application/json

{
    "transactionsID":[
        "67a7ece769e631a7e590fb15",
        "67a7ece769e631a7e590fb18"
    ]
}


###

PUT {{transactionEP}}/update/679821b1c6cb7b470cfd8b84
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF3ZUBnbWFpbC5jb20iLCJpYXQiOjE3MzgwMTg1MjAsImV4cCI6MTczODEwNDkyMH0.G-6Ay4wK2Ho0Ob0EzpqYl90qTs4V9Mr6SYyuwRvFgP8


{
    "amount" : 500,
    "description" : "sjkdfkashdglk",
    "type": "Expense"
}